### PR TITLE
Fix Multiple logouts issue

### LINKED ISSUE #111: Multiple Logout Prompts Following Assignment of New Mission to User
Whenever a user's team is assigned a new mission, the users in the team are forced to logout when online. This is to facilitate the pulling down of the new allocated missions. However, when a user signs in following a prompt the App will randomly issue additional logout even when there are no new missions assigned. A case in point is where a user working on v.0.1.7 says they were prompted over 7 times. Please have a look at what may be causing this.

### PR DESCRIPTION
**Pull request by hamza-vd**
Fixes #111

### CODE REVIEW

File: opensrp-eusm/src/main/java/org/smartregister/eusm/helper/AppValidateAssignmentHelper.java [hunk 1]
```diff
@@ -15,13 +15,21 @@ public AppValidateAssignmentHelper(SyncUtils syncUtils) {
...
-        return locationRepository.getAllLocations().stream().filter(location -> location.getProperties().getGeographicLevel() == 3).map(location -> location.getId()).collect(Collectors.toSet());
+        Set<String> regionIds = AppUtils.getLocationLevelFromLocationHierarchy(AppConstants.LocationLevels.REGION_TAG);
+        Set<String> districtIds = AppUtils.getLocationLevelFromLocationHierarchy(AppConstants.LocationLevels.DISTRICT_TAG);
+        Set<String> jurisdictionIds = EusmApplication.getInstance().context().userService().fetchJurisdictionIds();
+
+        // Remove district and region ids from assigned communes
+        jurisdictionIds.removeAll(districtIds);
+        jurisdictionIds.removeAll(regionIds);
+
+        return jurisdictionIds;
```
Comment (Rkareko) [inline opensrp-eusm/src/main/java/org/smartregister/eusm/helper/AppValidateAssignmentHelper.java:33]: @hamza-vd could you explain why this method is overridden? This will help shed some light on why district and region ids are being filtered out from the resulting set of jurisdictions

Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/helper/AppValidateAssignmentHelper.java:33]: We add `districts` and `regions` to communes (jurisdictions) that are returned at sign-in. It is required bcz it fetches these locations and saves them in the `Location` table of the app DB. So, to compare old assigned jurisdictions, we have to filter out regions and districts.

**Review by Rkareko — APPROVED** [review]
