### PR TITLE
Fix offline maps for regions

### LINKED ISSUE #114: Offline Maps Download Not Working
The offline Maps download on EUSM are not working. When a user  who is online selects a location and hits the download button, an error is returned that reads `Error: Location has no service points` See a sample screenshot below:

image

### PR DESCRIPTION
**Pull request by hamza-vd**
Closes #114

### CODE REVIEW

File: opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+        super.onDestroy();
+        fragmentPresenter = null;
+    }
+
+    @Override
+    public void deleteDownloadedOfflineMaps() {
+        displaySnackBar(getString(R.string.deleting_map));
+
+        for (OfflineMapModel offlineMapModel : downloadedOfflineMapModelList) {
+            if (offlineMapModel.getOfflineMapStatus().equals(OfflineMapModel.OfflineMapStatus.SELECTED_FOR_DOWNLOAD)) {
```
Comment (bennsimon) [inline opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java:139]:
```suggestion
            if (OfflineMapModel.OfflineMapStatus.SELECTED_FOR_DOWNLOAD.equals(offlineMapModel.getOfflineMapStatus)) {
```

File: opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java [hunk 2]
```diff
@@ -0,0 +1,172 @@
...
+    @Override
+    public void setOfflineMapDownloadCallback(OfflineMapDownloadCallback callBack) {
+        this.callback = callBack;
+    }
+
+    @Override
+    protected void mapDeletedSuccessfully(String deletedMapName) {
+        List<OfflineMapModel> toRemove = new ArrayList<>();
+        for (OfflineMapModel offlineMapModel : downloadedOfflineMapModelList) {
+            if (offlineMapModel.getDownloadAreaId().equals(deletedMapName)) {
```
Comment (bennsimon) [inline opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java:158]: Check for null on `deletedMapName`. Switch the args of the equal function. `(deletedMapName.equals(offlineMapModel.getDownloadAreaId))`

File: opensrp-eusm/src/main/java/org/smartregister/eusm/repository/AppStructureRepository.java [hunk 3]
```diff
@@ -272,7 +272,9 @@ public List<org.smartregister.domain.Location> getStructuresByDistrictId(String
         };
 
         String query = "SELECT " + StringUtils.join(columns, ",") + " from " + StructureRepository.STRUCTURE_TABLE
-                + " join location on location._id = " + StructureRepository.STRUCTURE_TABLE + ".parent_id ";
+                + " join location on location._id = " + StructureRepository.STRUCTURE_TABLE + ".parent_id"
+                + " AND " + StructureRepository.STRUCTURE_TABLE + "." + LATITUDE + " IS NOT NULL "
+                + " AND " + StructureRepository.STRUCTURE_TABLE + "." + LONGITUDE + " IS NOT NULL";
```
Comment (bennsimon) [inline opensrp-eusm/src/main/java/org/smartregister/eusm/repository/AppStructureRepository.java:277]: Is this function used anywhere else?

Comment (bennsimon) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/repository/AppStructureRepository.java:277]: Is there a scenario where this function is called and lat, lon are optional?

File: opensrp-eusm/src/test/java/org/smartregister/eusm/repository/AppLocationRepositoryTest.java [hunk 4]
```diff
@@ -65,4 +73,26 @@ public void testAddOrUpdateShouldInvokeAddLocationIfIdPresent() {
...
+
+            @Override
+            public Object answer(InvocationOnMock invocation) throws Throwable {
+                count++;
+                return count == 0;
+            }
+        }).when(cursor).moveToNext();
+
+        Set<Location> districts = appLocationRepository.getDistrictIdsForRegionId("23-3");
+        assertEquals(1, districts.size());
```
Comment (bennsimon) [inline opensrp-eusm/src/test/java/org/smartregister/eusm/repository/AppLocationRepositoryTest.java:95]: Could you assert that the method is actually called?

File: opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java [hunk 5]
```diff
@@ -0,0 +1,172 @@
...
+
+    @Override
+    public void displayError(int title, String message) {
+        // Do nothing
+    }
+
+    @Override
+    public void setDownloadedOfflineMapModelList(List<OfflineMapModel> downloadedOfflineMapModelList) {
+        if (adapter == null) {
+            this.downloadedOfflineMapModelList = downloadedOfflineMapModelList;
```
Comment (bennsimon) [inline opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java:63]: Is this necessary?

File: opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java [hunk 6]
```diff
@@ -514,15 +516,25 @@ public List<Location> getLocationsIdsForDownload(List<String> downloadedLocation
...
+
         if (downloadedLocations != null) {
-            jurisdictionIds.removeAll(downloadedLocations);
+            districtIds.removeAll(downloadedLocations);
         }
 //        List<Location> locationList =  EusmApplication.getInstance().getStructureRepository().getLocationByDistrictIds(jurisdictionIds);
 //
 //        if (downloadedLocations != null) {
 //            locationList = locationList.stream().filter(location -> !downloadedLocations.contains(location.getId())).collect(Collectors.toList());
 //        }
```
Comment (bennsimon) [inline opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java:536]: This can be cleaned up.

File: opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java [hunk 7]
```diff
@@ -0,0 +1,172 @@
...
+        }
+    }
+
+    @Override
+    public void updateOfflineMapsTodelete(View view) {
+        CheckBox checkBox = (CheckBox) view;
+        OfflineMapModel offlineMapModel = (OfflineMapModel) view.getTag(R.id.offline_map_checkbox);
+
+        for (OfflineMapModel model : downloadedOfflineMapModelList) {
+            if (model.getDownloadAreaId().equals(offlineMapModel.getDownloadAreaId())) {
```
Comment (bennsimon) [inline opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java:116]: check for null.

**Review by bennsimon — CHANGES_REQUESTED** [review]

File: opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java [hunk 8]
```diff
@@ -431,7 +433,7 @@ public String getProvinceFromTreeDialogValue(List<String> arrayList) {
     @Override
     public String getDistrictFromTreeDialogValue(List<String> arrayList) {
```
[the remark this answers is not in the document]
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java:434]: It is overridden method which is why its name cannot be changed. To rename the method we have to modify it in the tasking library.

File: opensrp-eusm/src/main/java/org/smartregister/eusm/repository/AppStructureRepository.java (hunk 3 above)
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/repository/AppStructureRepository.java:277]: Yes, I checked that earlier. There is only 1 usage of this method, we can safely modify it.

File: opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (bennsimon) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java:434]: Is the function used?

[the remark this answers is not in the document]
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java:434]: I can't find its usages but I saw an `Exception` thrown in logs because of the district level used here instead of region

[the remark this answers is not in the document]
Comment (bennsimon) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java:434]: Which exception?

**Review by bennsimon — CHANGES_REQUESTED** [review]

File: opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java:434]: I am unable to trace it now but it was an `IndexOutOfBoundException`

File: opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java [hunk 9]
```diff
@@ -431,7 +433,7 @@ public String getProvinceFromTreeDialogValue(List<String> arrayList) {
...
         try {
-            return arrayList.get(2);
+            return arrayList.get(1);
```
[the remark this answers is not in the document]
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java]: Done

File: opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java [hunk 10]
```diff
@@ -0,0 +1,172 @@
...
+        btnDeleteMap.setText(getString(R.string.delete).toUpperCase());
+        btnDeleteMap.setBackground(ContextCompat.getDrawable(requireContext(), R.drawable.delete_map_bg));
+
+        btnDeleteMap.setOnClickListener(v -> startDeleteProcess());
+    }
+
+    protected void startDeleteProcess() {
+        List<OfflineMapModel> mapsToDownload = new ArrayList<>();
+        for (OfflineMapModel offlineMapModel : downloadedOfflineMapModelList) {
+            if (offlineMapModel.getOfflineMapStatus().equals(OfflineMapModel.OfflineMapStatus.SELECTED_FOR_DOWNLOAD)) {
```
[the remark this answers is not in the document]
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java]: Updated

File: opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java (hunk 5 above)
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java]: Code refactored

File: opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java (hunk 6 above)
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/config/AppTaskingLibraryConfiguration.java]: Done

File: opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java (hunk 7 above)
Comment (hamza-vd) [reply opensrp-eusm/src/main/java/org/smartregister/eusm/fragment/EusmDownloadedOfflineMapsFragment.java]: Updated

**Review by bennsimon — APPROVED** [review]
